各スペシャル攻撃に音を付けられるように（今は暫定的に共通で音入れてます
Shi-553/ReLeaF pull request #18
Opened 2023-01-02 11:32 UTC by hikaru42731

特殊塗りボタン入力時にロボットの羽ばたき音（？）を追加←もしかしたらいらないかも
アイテム使用時になる音をInfoの方で0.5に調整

音探しはこれから行います。
確認お願いしますm(__)m

2023-01-02 12:00 UTC, Shi-553 commented
アイテム使用時の音があるので羽ばたきはいらないかもです
@緒方#3512 の意見も聞きたいです(メンションいくかな)

2023-01-02 12:04 UTC, Shi-553 commented
<@541558158724825098> テスト

2023-01-03 07:37 UTC, Shi-553 requested changes
ロボットの羽ばたき音を削除して欲しいです

2023-01-03 07:38 UTC, hikaru42731 commented
帰宅したら消します！

2023-01-03 11:04 UTC, hikaru42731 commented
羽ばたき音削除しました
すみません一回masterプルしちゃって余計なことしちゃったかもしれないです

2023-01-05 08:13 UTC, Shi-553 approved these changes
すいません遅くなりました
OKです

2023-01-05 08:13 UTC, merged